name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: actions-setup-cmake
      uses: jwlawson/actions-setup-cmake@v1.2
      with:
        cmake-version: '3.7.x'
    - name: install pkg-config
      run: sudo apt-get install pkg-config
    - name: install uuid-dev
      run: sudo apt-get install uuid-dev
    - name: install antlr4
      run: sudo apt-get install antlr4
    - name: Install Z3
      uses: pavpanchekha/setup-z3@v1.2
      with:
              version: 4.8.7
              architecture: x64
    - name: Copy Directories
      run: mkdir include/z3 && cp z3-4.8.7-x64-ubuntu-16.04/include/* include/z3
    - name: configure
      run: mkdir build && cd build && cmake -DWITH_TEST=ON ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ./tests/tests
      env:
        LD_LIBRARY_PATH: .
