name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Z3
      uses: pavpanchekha/setup-z3@v1.2
    - name: configure
      run: mkdir build && cd build && cmake -DWITH_TEST=ON ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
